# These are supported funding model platforms

github: Phoenix616
custom: ['https://acrobot-paypal.phoenix616.dev', 'https://tip.phoenix616.dev']
issuehunt: ChestShop-authors/ChestShop-3
ko_fi: Phoenix616
