files:
  - source: /plugin/src/main/resources/languages/lang.en.yml
    translation: /plugin/src/main/resources/languages/lang.%two_letters_code%.yml
    languages_mapping:
      two_letters_code:
        zh-TW: zh_TW
        pt-BR: pt_BR
        es-MX: es_MX
        en-PT: en_PT
