name: Bug report
description: Report an error that happens in the plugin.
labels: ["unconfirmed bug"]
body:
  - type: markdown
    attributes:
      value: >
        Please check if there are already similar issues open, also please test if your issue
        isn't already fixed by trying the latest development build: https://ci.minebench.de/job/ChestShop-3/

  - type: textarea
    attributes:
      label: What is happening?
      description: Explain what happens and what steps should be done to reproduce the issue. Ideally with pictures and the full error log!
    validations:
      required: true

  - type: textarea
    attributes:
      label: What did you expect to happen?
      description: Explain what you expected to happen after performing the previously described steps
    validations:
      required: true

  - type: input
    attributes:
      label: Plugin Version
      description: The full plugin version that you are running from `/version ChestShop`
    validations:
      required: true
  - type: checkboxes
    attributes:
      label: Version Check
      description: Please make sure your specified version meets the following. If it doesn't then your issue can most likely be resolved by updating.
      options:
        - label: It is the latest development version available from https://ci.minebench.de/job/ChestShop-3/.
        - label: The version [has support](https://github.com/ChestShop-authors/ChestShop-3/security/policy#supported-versions) for this type of issue.
          required: true
  - type: textarea
    attributes:
      label: Plugin Config
      description: The full `config.yml` file of ChestShop.
      value:  |
        <details>
          <summary>Config</summary>

         ```yaml
         PUT THE CONFIG HERE, DO NOT REPLACE THE WHOLE TEXT!
         ```

        </details>
    validations:
      required: true

  - type: input
    attributes:
      label: Server Version
      description: The full server version that you are running from `/version`.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Server Log
      description: The full `latest.log` file, especially important if you have a stack trace
      value: |
        <details>
          <summary>Log</summary>

          ```
         PUT YOUR LOG HERE, DO NOT REPLACE THE WHOLE TEXT!
          ```

        </details>
    validations:
      required: true
  - type: textarea
    attributes:
      label: What other plugins are you running?
      description: List of your plugins, ideally with the version
    validations:
      required: true

  - type: checkboxes
    attributes:
      label: Agreements
      description: Please agree to the following.
      options:
        - label: I have checked if there are already similar issues open.
        - label: I have provided all requested information and agree to the terms of the [project's license](https://github.com/ChestShop-authors/ChestShop-3/blob/master/LICENSE), especially the part about no warranty.
          required: true

  - type: textarea
    attributes:
      label: Additional context
      description: Add any other context or screenshots about the feature request here.