name: Enhancement
description: Request a feature or suggest an idea for this project
labels: [enhancement]
body:
  - type: markdown
    attributes:
      value: >
       Please check if there are already similar issues open, also please test if your request
       isn't already implemented by trying the latest development build: https://ci.minebench.de/job/ChestShop-3/

  - type: textarea
    attributes:
      label: Is your feature request related to a problem? Please describe.
      description: A clear and concise description of what the problem is. Ex. I'm always frustrated when...
    validations:
      required: true

  - type: textarea
    attributes:
      label: Describe the solution you'd like
      description: A clear and concise description of what you want to happen.
    validations:
      required: true

  - type: textarea
    attributes:
      label: Describe alternatives you've considered
      description: A clear and concise description of any alternative solutions or features you've considered.

  - type: checkboxes
    attributes:
      label: Agreements
      description: Please agree to the following.
      options:
        - label: I have checked if there are already similar issues open.
          required: true
        - label: I have checked that the [latest build](https://ci.minebench.de/job/ChestShop-3/) doesn't already implement the feature.
          required: true

  - type: textarea
    attributes:
      label: Additional context
      description: Add any other context or screenshots about the feature request here.
